version: '3'

services:
  web:
    build: .
    command: npm start
    container_name: task-conveyor-web
    depends_on:
      - redis
    # env_file loads .env into the container's env; docker-compose loads .env
    # by default for specifying ${} variables within the docker-compose.yml
    env_file: .env
    image: task-conveyor/task-conveyor:latest
    networks:
      task-conveyor:
        aliases:
          - web
    ports:
      - ${PORT}:${PORT}
    restart: 'no'
    volumes:
      - /app/node_modules/
      - .:/app:delegated

  redis:
    command: redis-server --appendonly yes
    container_name: task-conveyor-redis
    image: redis:3.2-alpine
    networks:
      task-conveyor:
        aliases:
         - redis
    volumes:
      - task-conveyor-data:/data

volumes:
  task-conveyor-data:

networks:
  task-conveyor:
